name: chad
description: OpenAI Chat API UI
repository: https://github.com/ivribalko/chad

publish_to: none

version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dart_openai: ^1.9.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  markdown_widget: ^2.1.0
  material_design_icons_flutter: ^6.0.7096
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1
  rename: ^2.1.1

flutter:
  assets:
    - env
  uses-material-design: true
