name: flutter_app_template
description: Quick start template
repository: https://github.com/ivribalko/flutter_app_template

publish_to: none

version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dart_openai: ^1.9.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  rename: ^2.1.1

flutter:
  uses-material-design: true
