name: Deploy to Firebase Hosting

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> env
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.9
          channel: stable
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAD_382603 }}'
          projectId: chad-382603
